#!/bin/bash
set -x
# Give access to Elixir module
chmod +x ./lib/program.ex

# Get arg passed to program.sh
token=$1

# Get regex based on pattern sequence
regex=$(mix run -e "Program.main('${token}')" <&-)

# Getting matches using regex
pcre2grep "${regex}"

